version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_container_2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - outro_volume:/var/lib/mysql
volumes:
  outro_volume: