server:
  error:
    include-stacktrace: on_param

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: spring-essentials
  datasource:
    url: jdbc:mysql://localhost:3306/dbanime?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace

management:
  endpoints:
    web:
      exposure:
        include:
          "*"
info:
  app: spring-anime

security:
  token:
    secret: ${SECRET_KEY}
